### ISSUE TITLE
Failed to run 'sass --stdin --scss -t compressed'

### ISSUE THREAD

**Issue by eserte** [jhthorsen/mojolicious-plugin-fontawesome4#2]
On CPAN Testers there are a couple of a fail reports like this one: http://www.cpantesters.org/cpan/report/8ad652be-522c-11e5-aed1-7f965b6afd5c

Overview: http://matrix.cpantesters.org/?dist=Mojolicious-Plugin-FontAwesome4%204.2004

**Comment by jhthorsen** [comment]
I've not fixed this issue. Instead I've removed the plugin from cpan, since it is no longer required with the new version of AssetPack.
