### ISSUE TITLE
support Font Awesome v4.5.0

### ISSUE THREAD

**Issue by keedi** [jhthorsen/mojolicious-plugin-fontawesome4#3]
Hi,

I usually use `M::P::FA4` when I want to handle Font Awesome without bower. This module is really neat for my simple work. I have some questions about release or update policy of this module.

- Current version of Font Awesome is v4.5.0, and module is including v4.2.0. Do you have a update plan?
- When sending pull request to update `M::P::FA4` following up official Font Awesome changes, do I have to update another static files like `/css`, `/fonts`, `/less`, `Gemfile` ... etc. Or is it enough to change files which are under `/lib/Mojolicious/Plugin/FontAwesome4/*`?

Anyway, thanks about `M::P::AssetPack` & `M::P::FA4`. I really like them since these modules are too convenient when I make simple web app with Perl. :)

**Comment by jhthorsen** [comment]
Hi, Thanks for reminding me :+1: 

The procedure I use is as following:

```
git remote add fa https://github.com/FortAwesome/Font-Awesome.git
git remote update
git merge v4.5.0
# edit conflicting files
prove -l # will generate new /lib/Mojolicious/Plugin/FontAwesome4/* files
# remove/commit new files
git ship # custom git command for making a release
```

The new version is on it's way to CPAN
